# fly.toml app configuration file generated for blogapi on 2023-10-15T15:40:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blogapi"
primary_region = "sea"

[build]

[env]
  PORT= "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
